version: "3.9"

services:
  http-mock:
    image: wiremock/wiremock:3.7.0
    container_name: http-mock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    command:
      - "--verbose"
      - "--global-response-templating"
      - "--local-response-templating"

  mysql:
    image: mysql:8.1
    container_name: hexagon-mysql
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5